# This file performs all of the relavent statistical analysis. Specifically, 
# it loads in the database generated by munge_data, further processes the data,
# and then builds a logistic model relating change in airline price to a list
# of covariates.
# 
# Usage:
# 
# airline_data <- parse_data('flight_data_3.db')
# data.glm <- glm(DFARE ~ MARKET + CXR + QDAY + DDAY + DCHUNK + DMONTH + DTD + FARE, data = data, family = "binomial")
# cost <- function(r, pi=0) mean(abs(r-pi)>0.5)
# data.glm.error <- cv.glm(data, logit, cost, K=11)
##Displays Full list of summary statistics for the glm including p-values, standard errors and siginificance levels
# summary(data.glm)
# summary(data.glm.error)
##Displays a list of graphical results of the regression. For information on interpreting the results see this page
##http://faculty1.ucmerced.edu/sdepaoli/docs/HW%206%20-%20notes%20to%20go%20over%20with%20them%20for%20the%20diagnostic%20plots%20before%20handing%20out%20HW.pdf
# plot(data.glm)
# 
library(RSQLite)
library(ggplot2)
library(gdata)
library(boot)

query_db <- function(sql,db) {

	drv <- dbDriver('SQLite')
	con <- dbConnect(drv, db)
	res <- dbGetQuery(con, sql)

}

parse_data <- function(db) {

	print('Loading Data')
  	data <- query_db('SELECT QDATE, MARKET, CXR, DDATE, DTIME, DFLIGHT, FARE, DFARE from flightdata',db)

	#Convert columns to appropriate data type
  	data$QDATE <- as.Date(as.character(data$QDATE), '%Y%m%d%H%M')
	data$DDATE <- as.Date(data$DDATE, '%Y-%m-%d')
  	data$DTIME <- as.numeric(substring(data$DTIME,0,2))
	data$DFLIGHT <- as.numeric(data$DFLIGHT)
	data$FARE <- as.numeric(data$FARE)
	data$DFARE <- as.numeric(ifelse(data$DFARE < 0, NA_character_, as.numeric(data$DFARE)))

	#Generate additional columns
  print('Generating Additional Columns')
  	data$DTD <- as.numeric(difftime(data$DDATE,data$QDATE,units='days'))
	data$QDAY <- weekdays(data$QDATE)
	data$DDAY <- weekdays(data$DDATE)
  	data$DCHUNK <- ifelse(data$DTIME <= 9, 1, ifelse(data$DTIME <= 12, 2, ifelse(data$DTIME <= 17, 3, 4))) 
	data$DMONTH <- as.numeric(strftime(data$DDATE,'%m'))

	#Tag Factor columns
  print('Generating Factors')
	data$MARKET <- factor(data$MARKET)
	data$CXR <- factor(data$CXR)
	data$DFLIGHT <- factor(data$DFLIGHT)
	data$DTD <- factor(data$DTD)
	data$QDAY <- factor(data$QDAY)
	data$DDAY <- factor(data$DDAY)
	data$DCHUNK <- factor(data$DCHUNK)
	data$DMONTH <- factor(data$DMONTH)
  
	return(data[rowSums(is.na(data)) == 0,])
}

#Import Data
data <- parse_data('flight_data_3.db')
#Generate Logistic Model
data.glm <- glm(DFARE ~ MARKET + CXR + QDAY + DDAY + DCHUNK + DMONTH + DTD + FARE, data = data, family = "binomial")
cost <- function(r, pi=0) mean(abs(r-pi)>0.5)
#Compute Classifier Error
data.glm.error <- cv.glm(data, logit, cost, K=5)
print(data.glm.error$delta)
